=head1 NAME

Web::URL::Canonicalize - Canonicalize URLs as Web browsers do

=head1 DESCRIPTION

The C<Web::URL::Canonicalize> module parses, resolves, and
canonicalizes URLs as Web browsers do.

This module is DEPRECATED.  Use L<Web::URL> instead.

=head1 SPECIFICATION

URL Standard <https://url.spec.whatwg.org/>.

=head1 SEE ALSO

L<Web::URL>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2011-2016 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
