=head1 NAME

Web::URL::Canonicalize - Canonicalize URLs as Web browsers do

=head1 DESCRIPTION

The C<Web::URL::Canonicalize> module parses, resolves, and
canonicalizes URLs as Web browsers do.

This module is DEPRECATED.  Use L<Web::URL> instead.

=head1 FUNCTION

There is the following function:

=over 4

=item $port = Web::URL::Canonicalize::get_default_port $scheme

Return the default port <https://url.spec.whatwg.org/#default-port>
for the scheme.  The argument must be a canonicalized (lowercase) URL
scheme.  If no default port is defined for the scheme, C<undef> is
returned.

=back

=head1 SPECIFICATION

URL Standard <https://url.spec.whatwg.org/>.

=head1 SEE ALSO

L<Web::URL>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2011-2016 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
