before_install: git submodule update --init
install: "PMBP_PERL_VERSION=5.14.2 make deps"
script: "PMBP_PERL_VERSION=5.14.2 make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "irc.suikawiki.org#mechanize"
    use_notice: true
