=head1 NAME

Web::DomainName::IDNEnabled - List of IDN-enabled TLDs

=head1 SYNOPSIS

  use Web::DomainName::IDNEnabled;
  ok $Web::DomainName::IDNEnabled::TLDs->{jp};
  ng $Web::DomainName::IDNEnabled::TLDs->{arpa};

=head1 DESCRIPTION

The C<Web::DomainName::IDNEnabled> module provides the list of
IDN-enabled TLDs, which is same as the list of the I<IDN-enabled TLDs>
maintained by the Mozilla project.

Note that the list is no longer maintained by the Mozilla project.

=head1 VARIABLE

The module defines a variable: C<$Web::DomainName::IDNEnabled::TLDs>.  It
is a hash reference.  Keys of the hash are IDN-enabled TLDs in
lowercase and is encoded in Punycode if necessary.  Values for
existing keys are always true.

=head1 SEE ALSO

IDN-enabled TLDs — Mozilla
<https://www.mozilla.org/en-US/about/governance/policies/security-group/tld-idn/>.

<https://github.com/mozilla/gecko-dev/blob/master/modules/libpref/init/all.js>.
(Search for C<network.IDN.whitelist.>.)

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

The C<Web::DomainName::IDNEnabled> module contains data extracted from
files maintained by the Mozilla project.

=head1 LICENSE

Copyright 2011-2015 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
