=head1 NAME

Web::IPAddr::Canonicalize - Canonicalize IPv4 and IPv6 addresses

=head1 DESCRIPTION

The C<Web::IPAddr::Canonicalize> module exports two functions to
canonicalize IP addresses as Web browsers do.

This module is DEPRECATED.  Use L<Web::Host> instead.

=head1 SEE ALSO

L<Web::Host>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2011-2016 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
